### ISSUE TITLE
[jwt][BE] OAuth 토큰 인증 방식

### ISSUE THREAD

**Issue by EarlyHail** [boostcamp-2020/IssueTracker-39#50]
- Front의 OAuth (Github) GET 요청을 받아 Github로 리다이렉팅
- github 로그인 성공 후 들어오는 callback 처리
  유저 DB 확인, 없으면 추가, 있으면 다음 과정
- jwt 토큰 발행
  - jwt 토큰을 임시로 cookie에 저장 후 메인 페이지와 함께 리턴
  - ` {"token": ${token}}`

**Comment by yyjjjj** [comment]
중복된 이슈 close
